// Code generated by protoc-gen-go.
// source: response.proto
// DO NOT EDIT!

/*
Package cflux is a generated protocol buffer package.

It is generated from these files:
	response.proto

It has these top-level messages:
	ClusterResponse
*/
package cflux

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ClusterResponse struct {
	Success          *bool   `protobuf:"varint,1,req,name=Success" json:"Success,omitempty"`
	Version          *string `protobuf:"bytes,2,req,name=Version" json:"Version,omitempty"`
	Message          *string `protobuf:"bytes,3,opt,name=Message" json:"Message,omitempty"`
	Data             *string `protobuf:"bytes,4,opt,name=Data" json:"Data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ClusterResponse) Reset()                    { *m = ClusterResponse{} }
func (m *ClusterResponse) String() string            { return proto.CompactTextString(m) }
func (*ClusterResponse) ProtoMessage()               {}
func (*ClusterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ClusterResponse) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *ClusterResponse) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

func (m *ClusterResponse) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *ClusterResponse) GetData() string {
	if m != nil && m.Data != nil {
		return *m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*ClusterResponse)(nil), "cflux.ClusterResponse")
}

func init() { proto.RegisterFile("response.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 116 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x4a, 0x2d, 0x2e,
	0xc8, 0xcf, 0x2b, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4d, 0x4e, 0xcb, 0x29,
	0xad, 0x50, 0x0a, 0xe2, 0xe2, 0x77, 0xce, 0x29, 0x2d, 0x2e, 0x49, 0x2d, 0x0a, 0x82, 0xca, 0x0b,
	0xf1, 0x73, 0xb1, 0x07, 0x97, 0x26, 0x27, 0xa7, 0x16, 0x17, 0x4b, 0x30, 0x2a, 0x30, 0x69, 0x70,
	0x80, 0x04, 0xc2, 0x52, 0x8b, 0x8a, 0x33, 0xf3, 0xf3, 0x24, 0x98, 0x80, 0x02, 0x9c, 0x20, 0x01,
	0x5f, 0xa0, 0x74, 0x62, 0x7a, 0xaa, 0x04, 0xb3, 0x02, 0x23, 0x50, 0x80, 0x87, 0x8b, 0xc5, 0x25,
	0xb1, 0x24, 0x51, 0x82, 0x05, 0xc4, 0x03, 0x04, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x77, 0x79, 0x50,
	0x6b, 0x00, 0x00, 0x00,
}
